export enum Permission {
  USERS_READ = 'users:read',
  USERS_WRITE = 'users:write',
  USERS_INVITE = 'users:invite',
  USERS_DELETE = 'users:delete',
  USERS_MANAGE_ROLES = 'users:manage_roles',
  POLICIES_READ = 'policies:read',
  POLICIES_WRITE = 'policies:write',
  POLICIES_DELETE = 'policies:delete',
  POLICIES_CALCULATE = 'policies:calculate',
  TRAVEL_REQUESTS_READ = 'travel_requests:read',
  TRAVEL_REQUESTS_READ_ALL = 'travel_requests:read_all',
  TRAVEL_REQUESTS_WRITE = 'travel_requests:write',
  TRAVEL_REQUESTS_SUBMIT = 'travel_requests:submit',
  TRAVEL_REQUESTS_CANCEL = 'travel_requests:cancel',
}
