export const ErrorCodes = {
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SLUG_EXISTS: 'TENANT_SLUG_EXISTS',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;
